id: posterr
name: Posterr
description: "Digital poster display for Plex, Sonarr and Radarr."
links:
  homepage: https://github.com/petersem/posterr
  documentation: https://github.com/petersem/posterr#readme
  source: https://github.com/petersem/posterr
  krate_docs: https://krate.github.io/docs/software/official/posterr
tier: free
category: tools
install_mode: local
autocomplete_options:
  - -b
ui_options:
  branches:
    - main
    - beta
